using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace ProjectEuler
{
    public partial class Default : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void okButton_Click(object sender, EventArgs e)
        {
            problem8();
        }

        protected void problem1()
        {
            //Problem 1:
            //If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.The sum of these multiples is 23.
            //Find the sum of all the multiples of 3 or 5 below 1000.
            
            int problemOneTotal = 0;
            for (int i = 0; i < 1000; i++)
            {
                if (i % 3 == 0 || i % 5 ==0) problemOneTotal += i;
            }
            resultLabel.Text = problemOneTotal.ToString();
        }

        protected void problem2()
        {
            //Problem 2:
            //EacH NEW TERM IN THE FIBONACCI SEQUENCE IS GENERATED BY ADDING THE PREVIOUS TWO TERMS.BY STARTING WITH 1 AND 2, THE FIRST 10 TERMS WILL BE:
            //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
            //BY Considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
            
            int currentNumber = 1;
            int lastNumber = 1;
            int total = 0;
            int fibonacciTotal = 0;
            while (currentNumber < 4000000)
            {
                if (currentNumber % 2 == 0) fibonacciTotal += currentNumber;
                total = currentNumber + lastNumber;
                lastNumber = currentNumber;
                currentNumber = total;
            }

            resultLabel.Text = fibonacciTotal.ToString();
        }

        protected void problem3()
        {
            //Problem 3:
            //The prime factors of 13195 are 5, 7, 13 and 29.
            //What is the largest prime factor of the number 600851475143 ?

            // What I know about primes: Every number (other than primes) can be found by multiplying primes (40 = 2*2*2*5, 39 = 3*13, etc.)

            long testNumber = 600851475143; 
            var primeList = new List<long>() { 2 };
            bool checkDivisible = true;
            
            for (long i = 3; i < testNumber; i += 2)
            {                
                // Check if number is prime.  Does this by seeing if it is divisible by any preceding prime numbers.
                foreach (var prime in primeList)
                {
                    if (i % prime == 0) { break; }
                    else if (prime == primeList.ElementAt(primeList.Count -1)) // if it was the last prime it was testing, the number must be prime if not divisible
                    {
                        primeList.Add(i);
                        checkDivisible = true;
                        while (checkDivisible) // divides the test number by the new prime until it is not divisible
                        {
                            if (testNumber % i == 0) { testNumber = testNumber / i; } // if divisible, breaks the number down to not loop through all the way to test number
                            else { checkDivisible = false; }
                        }
                        break; // primeList changes length and causes an error, needs to break out
                    }
                }
            }
            resultLabel.Text = testNumber.ToString();  // The remaining test number must be a prime and the largest prime 
        }

        protected void problem4()
        {
            //Problem 4:
            //A palindromic number reads the same both ways. The largest palindrome made from the product of two 2 - digit numbers is 9009 = 91 × 99.
            //Find the largest palindrome made from the product of two 3 - digit numbers.
            
            int highestPalindrome = 0;
            int firstNumber = 0;
            int secondNumber = 0;
            int k;
            string kStr;
            for (int i = 999; i > 0; i--)
            {
                for (int j = 999; j > 0; j--)
                {
                    k = i * j;
                    kStr = k.ToString();
                    if (k > highestPalindrome)
                    {
                        highestPalindrome = checkPalindrome(kStr) == "True" ? k : highestPalindrome;
                        firstNumber = i;
                        secondNumber = j;
                    }
                }
            }

            resultLabel.Text = String.Format("{0} ({1} x {2})",highestPalindrome.ToString(), firstNumber.ToString(), secondNumber.ToString());
        }

        protected void problem5()
        {
            //Problem 5:
            // 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
            // What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20 ?
            bool check = false;
            int i = 0;
            while (!check)
            {
                i += 2520;
                for (int j = 11; j < 21; j++)
                {
                    if (i % j != 0) { check = false;  break; }
                    else { check = true; }
                }
            }

            resultLabel.Text = i.ToString();
        }

        protected void problem6()
        {
            //Problem 6:
            //The sum of the squares of the first ten natural numbers is, 12 + 22 + ... + 102 = 385
            //The square of the sum of the first ten natural numbers is, (1 + 2 + ... + 10)2 = 552 = 3025
            //Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.
            //Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

            double result = 0;
            double squareSum = 0;
            for (int i = 1; i < 101; i++)
            {
                result += Math.Pow(i,2);
                squareSum += i;
            }
            result = Math.Pow(squareSum,2) - result;

            resultLabel.Text = result.ToString();
        }

        protected void problem7()
        {
            //Problem 7:
            //By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
            //What is the 10 001st prime number ?

            var primeList = new List<long>() { 2 };
            for (long i = 3; primeList.Count < 10001; i += 2)
            {
                // Check if number is prime.  Does this by seeing if it is divisible by any preceding prime numbers.
                foreach (var prime in primeList)
                {
                    if (i % prime == 0) { break; }
                    else if (prime == primeList.ElementAt(primeList.Count - 1)) // if it was the last prime it was testing, the number must be prime if not divisible
                    {
                        primeList.Add(i);
                        break; // primeList changes length and causes an error, needs to break out
                    }
                }
            }

            resultLabel.Text = primeList.ElementAt(primeList.Count - 1).ToString();
        }

        protected void problem8()
        {
            //Problem8()
            //The four adjacent digits in the 1000 - digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.
            //73167176531330624919225119674426574742355349194934
            //96983520312774506326239578318016984801869478851843
            //85861560789112949495459501737958331952853208805511
            //12540698747158523863050715693290963295227443043557
            //66896648950445244523161731856403098711121722383113
            //62229893423380308135336276614282806444486645238749
            //30358907296290491560440772390713810515859307960866
            //70172427121883998797908792274921901699720888093776
            //65727333001053367881220235421809751254540594752243
            //52584907711670556013604839586446706324415722155397
            //53697817977846174064955149290862569321978468622482
            //83972241375657056057490261407972968652414535100474
            //82166370484403199890008895243450658541227588666881
            //16427171479924442928230863465674813919123162824586
            //17866458359124566529476545682848912883142607690042
            //24219022671055626321111109370544217506941658960408
            //07198403850962455444362981230987879927244284909188
            //84580156166097919133875499200524063689912560717606
            //05886116467109405077541002256983155200055935729725
            //71636269561882670428252483600823257530420752963450
            //Find the thirteen adjacent digits in the 1000 - digit number that have the greatest product. What is the value of this product ?

            string thousandNumber = "73167176531330624919225119674426574742355349194934" +
                "96983520312774506326239578318016984801869478851843" +
                "85861560789112949495459501737958331952853208805511" +
                "12540698747158523863050715693290963295227443043557" +
                "66896648950445244523161731856403098711121722383113" +
                "62229893423380308135336276614282806444486645238749" +
                "30358907296290491560440772390713810515859307960866" +
                "70172427121883998797908792274921901699720888093776" +
                "65727333001053367881220235421809751254540594752243" +
                "52584907711670556013604839586446706324415722155397" +
                "53697817977846174064955149290862569321978468622482" +
                "83972241375657056057490261407972968652414535100474" +
                "82166370484403199890008895243450658541227588666881" +
                "16427171479924442928230863465674813919123162824586" +
                "17866458359124566529476545682848912883142607690042" +
                "24219022671055626321111109370544217506941658960408" +
                "07198403850962455444362981230987879927244284909188" +
                "84580156166097919133875499200524063689912560717606" +
                "05886116467109405077541002256983155200055935729725" +
                "71636269561882670428252483600823257530420752963450";

            int firstIndex = 0;
            int lastIndex = 12;
            long maxProduct = 0;
            long currentProduct = 0;

            while (lastIndex < 1000)
            {
                currentProduct = 1;
                for (int i = firstIndex; i < lastIndex + 1; i++)
                { currentProduct = currentProduct * (int)Char.GetNumericValue(thousandNumber[i]); }
                if (currentProduct > maxProduct) { maxProduct = currentProduct; }
                firstIndex++;
                lastIndex++;
            }

            resultLabel.Text = maxProduct.ToString();
        }

        protected void problem9()
        {

        }

        protected string checkPalindrome(string number)
        {
            string j = number; //Number you are testing for palindrome
            int k = int.Parse(j);
            string result = "True";
            for (k = 0; k < j.Length; k++)
            {
                if (j[k] != j[j.Length - k - 1])
                {
                    result = "False";
                    break;
                }
            }

            return result;
        }
    }
}